version: '3'

services:
  fess:
    build: ./fess
    restart: always
    environment:
      TZ:  Asia/Tokyo
      RUN_ELASTICSEARCH: "true"
      FESS_DICTIONARY_PATH: /usr/share/elasticsearch/config/dictionary/
      FESS_CONTEXT_PATH: ${FESS_CONTEXT_PATH}
    volumes:
      - fess_data:/opt/fess
      - elasticsearch_data:/var/lib/elasticsearch
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m
    ports:
      - ${FESS_PORT}:8080
volumes:
  fess_data:
    driver_opts:
      type: none
      device: ./volumes/fess_data/
      o: bind
  elasticsearch_data:
    driver_opts:
      type: none
      device: ./volumes/elasticsearch_data/
      o: bind